---
title: "Predicting On-Time Flight Departures"
author: "Joseph Kerkhof"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exploring the data

```{r}
cleanDataset = function(flight.data){
  # Removing unusable variables
  keeps = c(
    "DAY_OF_MONTH",
    "DAY_OF_WEEK",
    "OP_CARRIER",
    "TAIL_NUM",
    "ORIGIN",
    "DEST",
    "DEP_TIME",
    "DEP_DEL15",
    "DEP_TIME_BLK",
    "ARR_TIME",
    "ARR_DEL15",
    "CANCELLED",
    "DIVERTED",
    "DISTANCE"
  )
  flight.data = flight.data[keeps]
  
  # Converting ints to factors
  flight.data$DAY_OF_MONTH = as.factor(flight.data$DAY_OF_MONTH)
  flight.data$DAY_OF_WEEK = as.factor(flight.data$DAY_OF_WEEK)
  flight.data$DEP_DEL15 = as.factor(flight.data$DEP_DEL15)
  flight.data$DEP_TIME_BLK = as.factor(flight.data$DEP_TIME_BLK)
  flight.data$ARR_DEL15 = as.factor(flight.data$ARR_DEL15)
  flight.data$CANCELLED = as.factor(flight.data$CANCELLED)
  flight.data$DIVERTED = as.factor(flight.data$DIVERTED)
  
  # Removing any rows with incomplete data
  flight.data = flight.data[which(complete.cases(flight.data) == TRUE),]

  return(flight.data)
}

jan19 = read.csv('./data/Jan_2019_ontime.csv')
jan20 = read.csv('./data/Jan_2020_ontime.csv')

jan19 = cleanDataset(jan19)
```

## First method: Logistic Regression


